using System.Collections.Generic;
using System.Linq;

namespace ff8_card_manip
{
    public class CardTable
    {
        private static Card[] _table = new[]
        {
            new Card()
            {
                Id = 0,
                Urdl = new int[] {1, 4, 1, 5},
                Urdl_s = "1415",
                Level = 1,
                Row = 1,
                Name = "ハウリザード",
                Name_e = "Geezard",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 1,
                Urdl = new int[] {5, 1, 1, 3},
                Urdl_s = "5113",
                Level = 1,
                Row = 2,
                Name = "フンゴオンゴ",
                Name_e = "Funguar",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 2,
                Urdl = new int[] {1, 3, 3, 5},
                Urdl_s = "1335",
                Level = 1,
                Row = 3,
                Name = "バイトバグ",
                Name_e = "Bite Bug",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 3,
                Urdl = new int[] {6, 1, 1, 2},
                Urdl_s = "6112",
                Level = 1,
                Row = 4,
                Name = "レッドマウス",
                Name_e = "Red Bat",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 4,
                Urdl = new int[] {2, 3, 1, 5},
                Urdl_s = "2315",
                Level = 1,
                Row = 5,
                Name = "プリヌラ",
                Name_e = "Blobra",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 5,
                Urdl = new int[] {2, 1, 4, 4},
                Urdl_s = "2144",
                Level = 1,
                Row = 6,
                Name = "ゲイラ",
                Name_e = "Gayla",
                Element = Card.TElement.Thunder,
                Rare = false,
            },
            new Card()
            {
                Id = 6,
                Urdl = new int[] {1, 5, 4, 1},
                Urdl_s = "1541",
                Level = 1,
                Row = 7,
                Name = "ゲスパー",
                Name_e = "Gesper",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 7,
                Urdl = new int[] {3, 5, 2, 1},
                Urdl_s = "3521",
                Level = 1,
                Row = 8,
                Name = "フォカロルフェイク",
                Name_e = "Fastitocalon-F",
                Element = Card.TElement.Earth,
                Rare = false,
            },
            new Card()
            {
                Id = 8,
                Urdl = new int[] {2, 1, 6, 1},
                Urdl_s = "2161",
                Level = 1,
                Row = 9,
                Name = "ブラットソウル",
                Name_e = "Blood Soul",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 9,
                Urdl = new int[] {4, 2, 4, 3},
                Urdl_s = "4243",
                Level = 1,
                Row = 10,
                Name = "ケダチク",
                Name_e = "Caterchipillar",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 10,
                Urdl = new int[] {2, 1, 2, 6},
                Urdl_s = "2126",
                Level = 1,
                Row = 11,
                Name = "コカトリス",
                Name_e = "Cockatrice",
                Element = Card.TElement.Thunder,
                Rare = false,
            },
            new Card()
            {
                Id = 11,
                Urdl = new int[] {7, 1, 3, 1},
                Urdl_s = "7131",
                Level = 2,
                Row = 1,
                Name = "グラット",
                Name_e = "Grat",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 12,
                Urdl = new int[] {6, 2, 2, 3},
                Urdl_s = "6223",
                Level = 2,
                Row = 2,
                Name = "ブエル",
                Name_e = "Buel",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 13,
                Urdl = new int[] {5, 3, 3, 4},
                Urdl_s = "5334",
                Level = 2,
                Row = 3,
                Name = "メズマライズ",
                Name_e = "Mesmerize",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 14,
                Urdl = new int[] {6, 1, 4, 3},
                Urdl_s = "6143",
                Level = 2,
                Row = 4,
                Name = "グヘイスアイ",
                Name_e = "Glacial Eye",
                Element = Card.TElement.Ice,
                Rare = false,
            },
            new Card()
            {
                Id = 15,
                Urdl = new int[] {3, 4, 5, 3},
                Urdl_s = "3453",
                Level = 2,
                Row = 5,
                Name = "ベルヘルメルヘル",
                Name_e = "Belhelmel",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 16,
                Urdl = new int[] {5, 3, 2, 5},
                Urdl_s = "5325",
                Level = 2,
                Row = 6,
                Name = "スラストエイビス",
                Name_e = "Thrustaevis",
                Element = Card.TElement.Wind,
                Rare = false,
            },
            new Card()
            {
                Id = 17,
                Urdl = new int[] {5, 1, 3, 5},
                Urdl_s = "5135",
                Level = 2,
                Row = 7,
                Name = "ヘッジヴァイパー",
                Name_e = "Anacondaur",
                Element = Card.TElement.Poison,
                Rare = false,
            },
            new Card()
            {
                Id = 18,
                Urdl = new int[] {5, 2, 5, 2},
                Urdl_s = "5252",
                Level = 2,
                Row = 8,
                Name = "クリープス",
                Name_e = "Creeps",
                Element = Card.TElement.Thunder,
                Rare = false,
            },
            new Card()
            {
                Id = 19,
                Urdl = new int[] {4, 4, 5, 2},
                Urdl_s = "4452",
                Level = 2,
                Row = 9,
                Name = "グレンデル",
                Name_e = "Grendel",
                Element = Card.TElement.Thunder,
                Rare = false,
            },
            new Card()
            {
                Id = 20,
                Urdl = new int[] {3, 2, 1, 7},
                Urdl_s = "3217",
                Level = 2,
                Row = 10,
                Name = "ダブルハガー",
                Name_e = "Jelleye",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 21,
                Urdl = new int[] {5, 2, 5, 3},
                Urdl_s = "5253",
                Level = 2,
                Row = 11,
                Name = "グランデアーロ",
                Name_e = "Grand Mantis",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 22,
                Urdl = new int[] {6, 6, 3, 2},
                Urdl_s = "6632",
                Level = 3,
                Row = 1,
                Name = "ライフフォビドン",
                Name_e = "Forbidden",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 23,
                Urdl = new int[] {6, 3, 1, 6},
                Urdl_s = "6316",
                Level = 3,
                Row = 2,
                Name = "エサンスーシ",
                Name_e = "Armadodo",
                Element = Card.TElement.Earth,
                Rare = false,
            },
            new Card()
            {
                Id = 24,
                Urdl = new int[] {3, 5, 5, 5},
                Urdl_s = "3555",
                Level = 3,
                Row = 3,
                Name = "トライフェイス",
                Name_e = "Tri-Face",
                Element = Card.TElement.Poison,
                Rare = false,
            },
            new Card()
            {
                Id = 25,
                Urdl = new int[] {7, 5, 1, 3},
                Urdl_s = "7513",
                Level = 3,
                Row = 4,
                Name = "フォカロル",
                Name_e = "Fastitocalon",
                Element = Card.TElement.Water,
                Rare = false,
            },
            new Card()
            {
                Id = 26,
                Urdl = new int[] {7, 1, 5, 3},
                Urdl_s = "7153",
                Level = 3,
                Row = 5,
                Name = "ゴージュシール",
                Name_e = "Snow Lion",
                Element = Card.TElement.Ice,
                Rare = false,
            },
            new Card()
            {
                Id = 27,
                Urdl = new int[] {5, 6, 3, 3},
                Urdl_s = "5633",
                Level = 3,
                Row = 6,
                Name = "オチュー",
                Name_e = "Ochu",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 28,
                Urdl = new int[] {5, 6, 2, 4},
                Urdl_s = "5624",
                Level = 3,
                Row = 7,
                Name = "SAM08G",
                Name_e = "SAM08G",
                Element = Card.TElement.Fire,
                Rare = false,
            },
            new Card()
            {
                Id = 29,
                Urdl = new int[] {4, 4, 7, 2},
                Urdl_s = "4472",
                Level = 3,
                Row = 8,
                Name = "ワイルドフック",
                Name_e = "Death Claw",
                Element = Card.TElement.Fire,
                Rare = false,
            },
            new Card()
            {
                Id = 30,
                Urdl = new int[] {6, 2, 6, 3},
                Urdl_s = "6263",
                Level = 3,
                Row = 9,
                Name = "サボテンダー",
                Name_e = "Cactuar",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 31,
                Urdl = new int[] {3, 6, 4, 4},
                Urdl_s = "3644",
                Level = 3,
                Row = 10,
                Name = "トンベリ",
                Name_e = "Tonberry",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 32,
                Urdl = new int[] {7, 2, 3, 5},
                Urdl_s = "7235",
                Level = 3,
                Row = 11,
                Name = "アビスウォーム",
                Name_e = "Abyss Worm",
                Element = Card.TElement.Earth,
                Rare = false,
            },
            new Card()
            {
                Id = 33,
                Urdl = new int[] {2, 3, 6, 7},
                Urdl_s = "2367",
                Level = 4,
                Row = 1,
                Name = "グラナトゥム",
                Name_e = "Turtapod",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 34,
                Urdl = new int[] {6, 5, 4, 5},
                Urdl_s = "6545",
                Level = 4,
                Row = 2,
                Name = "バイセージ・ハンズ",
                Name_e = "Vysage",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 35,
                Urdl = new int[] {4, 6, 2, 7},
                Urdl_s = "4627",
                Level = 4,
                Row = 3,
                Name = "アルケオダイノス",
                Name_e = "T-Rexaur",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 36,
                Urdl = new int[] {2, 7, 6, 3},
                Urdl_s = "2763",
                Level = 4,
                Row = 4,
                Name = "ボム",
                Name_e = "Bomb",
                Element = Card.TElement.Fire,
                Rare = false,
            },
            new Card()
            {
                Id = 37,
                Urdl = new int[] {1, 6, 4, 7},
                Urdl_s = "1647",
                Level = 4,
                Row = 5,
                Name = "ブリッツ",
                Name_e = "Blitz",
                Element = Card.TElement.Thunder,
                Rare = false,
            },
            new Card()
            {
                Id = 38,
                Urdl = new int[] {7, 3, 1, 6},
                Urdl_s = "7316",
                Level = 4,
                Row = 6,
                Name = "ウェンディゴ",
                Name_e = "Wendigo",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 39,
                Urdl = new int[] {7, 4, 4, 4},
                Urdl_s = "7444",
                Level = 4,
                Row = 7,
                Name = "クアール",
                Name_e = "Torama",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 40,
                Urdl = new int[] {3, 7, 3, 6},
                Urdl_s = "3736",
                Level = 4,
                Row = 8,
                Name = "ガルキマセラ",
                Name_e = "Imp",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 41,
                Urdl = new int[] {6, 2, 7, 3},
                Urdl_s = "6273",
                Level = 4,
                Row = 9,
                Name = "ドラゴンイゾルデ",
                Name_e = "Blue Dragon",
                Element = Card.TElement.Poison,
                Rare = false,
            },
            new Card()
            {
                Id = 42,
                Urdl = new int[] {4, 5, 5, 6},
                Urdl_s = "4556",
                Level = 4,
                Row = 10,
                Name = "アダマンタイマイ",
                Name_e = "Adamantoise",
                Element = Card.TElement.Earth,
                Rare = false,
            },
            new Card()
            {
                Id = 43,
                Urdl = new int[] {7, 5, 4, 3},
                Urdl_s = "7543",
                Level = 4,
                Row = 11,
                Name = "メルトドラゴン",
                Name_e = "Hexadragon",
                Element = Card.TElement.Fire,
                Rare = false,
            },
            new Card()
            {
                Id = 44,
                Urdl = new int[] {6, 5, 6, 5},
                Urdl_s = "6565",
                Level = 5,
                Row = 1,
                Name = "鉄巨人",
                Name_e = "Iron Giant",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 45,
                Urdl = new int[] {3, 6, 5, 7},
                Urdl_s = "3657",
                Level = 5,
                Row = 2,
                Name = "ベヒーモス",
                Name_e = "Behemoth",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 46,
                Urdl = new int[] {7, 6, 5, 3},
                Urdl_s = "7653",
                Level = 5,
                Row = 3,
                Name = "キマイラブレイン",
                Name_e = "Chimera",
                Element = Card.TElement.Water,
                Rare = false,
            },
            new Card()
            {
                Id = 47,
                Urdl = new int[] {3, 10, 2, 1},
                Urdl_s = "3a21",
                Level = 5,
                Row = 4,
                Name = "コヨコヨ",
                Name_e = "PuPu",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 48,
                Urdl = new int[] {6, 2, 6, 7},
                Urdl_s = "6267",
                Level = 5,
                Row = 5,
                Name = "インビンシブル",
                Name_e = "Elastoid",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 49,
                Urdl = new int[] {5, 5, 7, 4},
                Urdl_s = "5574",
                Level = 5,
                Row = 6,
                Name = "GIM47N",
                Name_e = "GIM47N",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 50,
                Urdl = new int[] {7, 7, 4, 2},
                Urdl_s = "7742",
                Level = 5,
                Row = 7,
                Name = "モルボル",
                Name_e = "Malboro",
                Element = Card.TElement.Poison,
                Rare = false,
            },
            new Card()
            {
                Id = 51,
                Urdl = new int[] {7, 2, 7, 4},
                Urdl_s = "7274",
                Level = 5,
                Row = 8,
                Name = "ルブルムドラゴン",
                Name_e = "Ruby Dragon",
                Element = Card.TElement.Fire,
                Rare = false,
            },
            new Card()
            {
                Id = 52,
                Urdl = new int[] {5, 3, 7, 6},
                Urdl_s = "5376",
                Level = 5,
                Row = 9,
                Name = "エルノーイル",
                Name_e = "Elnoyle",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 53,
                Urdl = new int[] {4, 6, 7, 4},
                Urdl_s = "4674",
                Level = 5,
                Row = 10,
                Name = "トンベリキング",
                Name_e = "Tonberry King",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 54,
                Urdl = new int[] {6, 6, 2, 7},
                Urdl_s = "6627",
                Level = 5,
                Row = 11,
                Name = "ウェッジ・ビッグス",
                Name_e = "Wedge Biggs",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 55,
                Urdl = new int[] {2, 8, 8, 4},
                Urdl_s = "2884",
                Level = 6,
                Row = 1,
                Name = "風神・雷神",
                Name_e = "Fujin Raijin",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 56,
                Urdl = new int[] {7, 8, 3, 4},
                Urdl_s = "7834",
                Level = 6,
                Row = 2,
                Name = "エルヴィオレ",
                Name_e = "Elvoret",
                Element = Card.TElement.Wind,
                Rare = false,
            },
            new Card()
            {
                Id = 57,
                Urdl = new int[] {4, 8, 7, 3},
                Urdl_s = "4873",
                Level = 6,
                Row = 3,
                Name = "X-ATM092",
                Name_e = "X-ATM092",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 58,
                Urdl = new int[] {7, 2, 8, 5},
                Urdl_s = "7285",
                Level = 6,
                Row = 4,
                Name = "グラナルド",
                Name_e = "Granaldo",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 59,
                Urdl = new int[] {1, 8, 8, 3},
                Urdl_s = "1883",
                Level = 6,
                Row = 5,
                Name = "ナムタル・ウトク",
                Name_e = "Gerogero",
                Element = Card.TElement.Poison,
                Rare = false,
            },
            new Card()
            {
                Id = 60,
                Urdl = new int[] {8, 2, 8, 2},
                Urdl_s = "8282",
                Level = 6,
                Row = 6,
                Name = "シュメルケ",
                Name_e = "Iguion",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 61,
                Urdl = new int[] {6, 8, 4, 5},
                Urdl_s = "6845",
                Level = 6,
                Row = 7,
                Name = "アバドン",
                Name_e = "Abadon",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 62,
                Urdl = new int[] {4, 8, 5, 6},
                Urdl_s = "4856",
                Level = 6,
                Row = 8,
                Name = "ドルメン",
                Name_e = "Trauma",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 63,
                Urdl = new int[] {1, 8, 4, 8},
                Urdl_s = "1848",
                Level = 6,
                Row = 9,
                Name = "オイルシッパー",
                Name_e = "Oilboyle",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 64,
                Urdl = new int[] {6, 5, 8, 4},
                Urdl_s = "6584",
                Level = 6,
                Row = 10,
                Name = "シュミ族",
                Name_e = "Shumi Tribe",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 65,
                Urdl = new int[] {7, 5, 8, 1},
                Urdl_s = "7581",
                Level = 6,
                Row = 11,
                Name = "コキュートス",
                Name_e = "Krysta",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 66,
                Urdl = new int[] {8, 4, 4, 8},
                Urdl_s = "8448",
                Level = 7,
                Row = 1,
                Name = "プロパゲーター",
                Name_e = "Propagator",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 67,
                Urdl = new int[] {8, 8, 4, 4},
                Urdl_s = "8844",
                Level = 7,
                Row = 2,
                Name = "ジャボテンダー",
                Name_e = "Jumbo Cactuar",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 68,
                Urdl = new int[] {8, 5, 2, 8},
                Urdl_s = "8528",
                Level = 7,
                Row = 3,
                Name = "トライエッジ",
                Name_e = "Tri-Point",
                Element = Card.TElement.Thunder,
                Rare = false,
            },
            new Card()
            {
                Id = 69,
                Urdl = new int[] {5, 6, 6, 8},
                Urdl_s = "5668",
                Level = 7,
                Row = 4,
                Name = "ガルガンチュア",
                Name_e = "Gargantua",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 70,
                Urdl = new int[] {8, 6, 7, 3},
                Urdl_s = "8673",
                Level = 7,
                Row = 5,
                Name = "機動兵器８型ＢＩＳ",
                Name_e = "Mobile Type 8",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 71,
                Urdl = new int[] {8, 3, 5, 8},
                Urdl_s = "8358",
                Level = 7,
                Row = 6,
                Name = "アンドロ",
                Name_e = "Sphinxara",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 72,
                Urdl = new int[] {8, 8, 5, 4},
                Urdl_s = "8854",
                Level = 7,
                Row = 7,
                Name = "ティアマト",
                Name_e = "Tiamat",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 73,
                Urdl = new int[] {5, 7, 8, 5},
                Urdl_s = "5785",
                Level = 7,
                Row = 8,
                Name = "BGH251F2",
                Name_e = "BGH251F2",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 74,
                Urdl = new int[] {6, 8, 4, 7},
                Urdl_s = "6847",
                Level = 7,
                Row = 9,
                Name = "ウルフラマイター",
                Name_e = "Red Giant",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 75,
                Urdl = new int[] {1, 8, 7, 7},
                Urdl_s = "1877",
                Level = 7,
                Row = 10,
                Name = "カトブレパス",
                Name_e = "Catoblepas",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 76,
                Urdl = new int[] {7, 7, 8, 2},
                Urdl_s = "7782",
                Level = 7,
                Row = 11,
                Name = "アルテマウェポン",
                Name_e = "Ultima Weapon",
                Element = Card.TElement.None,
                Rare = false,
            },
            new Card()
            {
                Id = 77,
                Urdl = new int[] {4, 4, 8, 9},
                Urdl_s = "4489",
                Level = 8,
                Row = 1,
                Name = "デブチョコボ",
                Name_e = "Chubby Chocobo",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 78,
                Urdl = new int[] {9, 6, 7, 3},
                Urdl_s = "9673",
                Level = 8,
                Row = 2,
                Name = "アンジェロ",
                Name_e = "Angelo",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 79,
                Urdl = new int[] {3, 7, 9, 6},
                Urdl_s = "3796",
                Level = 8,
                Row = 3,
                Name = "ギルガメッシュ",
                Name_e = "Gilgamesh",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 80,
                Urdl = new int[] {9, 3, 9, 2},
                Urdl_s = "9392",
                Level = 8,
                Row = 4,
                Name = "コモーグリ",
                Name_e = "MiniMog",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 81,
                Urdl = new int[] {9, 4, 8, 4},
                Urdl_s = "9484",
                Level = 8,
                Row = 5,
                Name = "コチョコボ",
                Name_e = "Chicobo",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 82,
                Urdl = new int[] {2, 9, 9, 4},
                Urdl_s = "2994",
                Level = 8,
                Row = 6,
                Name = "ケツァクウァトル",
                Name_e = "Quezacotl",
                Element = Card.TElement.Thunder,
                Rare = true,
            },
            new Card()
            {
                Id = 83,
                Urdl = new int[] {6, 7, 4, 9},
                Urdl_s = "6749",
                Level = 8,
                Row = 7,
                Name = "シヴァ",
                Name_e = "Shiva",
                Element = Card.TElement.Ice,
                Rare = true,
            },
            new Card()
            {
                Id = 84,
                Urdl = new int[] {9, 6, 2, 8},
                Urdl_s = "9628",
                Level = 8,
                Row = 8,
                Name = "イフリート",
                Name_e = "Ifrit",
                Element = Card.TElement.Fire,
                Rare = true,
            },
            new Card()
            {
                Id = 85,
                Urdl = new int[] {8, 9, 6, 2},
                Urdl_s = "8962",
                Level = 8,
                Row = 9,
                Name = "セイレーン",
                Name_e = "Siren",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 86,
                Urdl = new int[] {5, 1, 9, 9},
                Urdl_s = "5199",
                Level = 8,
                Row = 10,
                Name = "セクレト",
                Name_e = "Sacred",
                Element = Card.TElement.Earth,
                Rare = true,
            },
            new Card()
            {
                Id = 87,
                Urdl = new int[] {9, 5, 2, 9},
                Urdl_s = "9529",
                Level = 8,
                Row = 11,
                Name = "ミノタウロス",
                Name_e = "Minotaur",
                Element = Card.TElement.Earth,
                Rare = true,
            },
            new Card()
            {
                Id = 88,
                Urdl = new int[] {8, 4, 10, 4},
                Urdl_s = "84a4",
                Level = 9,
                Row = 1,
                Name = "カーバンクル",
                Name_e = "Carbuncle",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 89,
                Urdl = new int[] {5, 10, 8, 3},
                Urdl_s = "5a83",
                Level = 9,
                Row = 2,
                Name = "ディアボロス",
                Name_e = "Diablos",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 90,
                Urdl = new int[] {7, 10, 1, 7},
                Urdl_s = "7a17",
                Level = 9,
                Row = 3,
                Name = "リヴァイアサン",
                Name_e = "Leviathan",
                Element = Card.TElement.Water,
                Rare = true,
            },
            new Card()
            {
                Id = 91,
                Urdl = new int[] {8, 10, 3, 5},
                Urdl_s = "8a35",
                Level = 9,
                Row = 4,
                Name = "オーディン",
                Name_e = "Odin",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 92,
                Urdl = new int[] {10, 1, 7, 7},
                Urdl_s = "a177",
                Level = 9,
                Row = 5,
                Name = "パンデモニウム",
                Name_e = "Pandemonia",
                Element = Card.TElement.Wind,
                Rare = true,
            },
            new Card()
            {
                Id = 93,
                Urdl = new int[] {7, 4, 6, 10},
                Urdl_s = "746a",
                Level = 9,
                Row = 6,
                Name = "ケルベロス",
                Name_e = "Cerberus",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 94,
                Urdl = new int[] {9, 10, 4, 2},
                Urdl_s = "9a42",
                Level = 9,
                Row = 7,
                Name = "アレクサンダー",
                Name_e = "Alexander",
                Element = Card.TElement.Holy,
                Rare = true,
            },
            new Card()
            {
                Id = 95,
                Urdl = new int[] {7, 2, 7, 10},
                Urdl_s = "727a",
                Level = 9,
                Row = 8,
                Name = "フェニックス",
                Name_e = "Phoenix",
                Element = Card.TElement.Fire,
                Rare = true,
            },
            new Card()
            {
                Id = 96,
                Urdl = new int[] {10, 8, 2, 6},
                Urdl_s = "a826",
                Level = 9,
                Row = 9,
                Name = "バハムート",
                Name_e = "Bahumut",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 97,
                Urdl = new int[] {3, 1, 10, 10},
                Urdl_s = "31aa",
                Level = 9,
                Row = 10,
                Name = "グラシャラボラス",
                Name_e = "Doomtrain",
                Element = Card.TElement.Poison,
                Rare = true,
            },
            new Card()
            {
                Id = 98,
                Urdl = new int[] {4, 4, 9, 10},
                Urdl_s = "449a",
                Level = 9,
                Row = 11,
                Name = "エデン",
                Name_e = "Eden",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 99,
                Urdl = new int[] {10, 7, 2, 8},
                Urdl_s = "a728",
                Level = 10,
                Row = 1,
                Name = "ウォード",
                Name_e = "Ward",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 100,
                Urdl = new int[] {6, 7, 6, 10},
                Urdl_s = "676a",
                Level = 10,
                Row = 2,
                Name = "キロス",
                Name_e = "Kiros",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 101,
                Urdl = new int[] {5, 10, 3, 9},
                Urdl_s = "5a39",
                Level = 10,
                Row = 3,
                Name = "ラグナ",
                Name_e = "Laguna",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 102,
                Urdl = new int[] {10, 8, 6, 4},
                Urdl_s = "a864",
                Level = 10,
                Row = 4,
                Name = "セルフィ",
                Name_e = "Selphie",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 103,
                Urdl = new int[] {9, 6, 10, 2},
                Urdl_s = "96a2",
                Level = 10,
                Row = 5,
                Name = "キスティス",
                Name_e = "Quistis",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 104,
                Urdl = new int[] {2, 6, 9, 10},
                Urdl_s = "269a",
                Level = 10,
                Row = 6,
                Name = "アーヴァイン",
                Name_e = "Irvine",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 105,
                Urdl = new int[] {8, 5, 10, 6},
                Urdl_s = "85a6",
                Level = 10,
                Row = 7,
                Name = "ゼル",
                Name_e = "Zell",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 106,
                Urdl = new int[] {4, 10, 2, 10},
                Urdl_s = "4a2a",
                Level = 10,
                Row = 8,
                Name = "リノア",
                Name_e = "Rinoa",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 107,
                Urdl = new int[] {10, 10, 3, 3},
                Urdl_s = "aa33",
                Level = 10,
                Row = 9,
                Name = "イデア",
                Name_e = "Edea",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 108,
                Urdl = new int[] {6, 9, 10, 4},
                Urdl_s = "69a4",
                Level = 10,
                Row = 10,
                Name = "サイファー",
                Name_e = "Seifer",
                Element = Card.TElement.None,
                Rare = true,
            },
            new Card()
            {
                Id = 109,
                Urdl = new int[] {10, 4, 6, 9},
                Urdl_s = "a469",
                Level = 10,
                Row = 11,
                Name = "スコール",
                Name_e = "Squall",
                Element = Card.TElement.None,
                Rare = true,
            },
        };

        public static int FindIdByName(string name_e)
        {
            return _table.First(x => x.Name_e == name_e).Id;
        }

        public static string FindNameById(int id)
        {
            return _table.First(x => x.Id == id).Name_e;
        }

        public static IList<int> ListIdsByUrdl(IEnumerable<int> urdl, bool fuzzy = false)
        {
            if (fuzzy)
            {
                urdl = urdl.OrderBy(x => x);
            }

            return _table
                .Where(x => urdl.SequenceEqual(fuzzy ? x.Urdl.OrderBy(y => y).ToArray() : x.Urdl))
                .Select(x => x.Id)
                .ToList();
        }
    }
}
